
service: serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  getData:
    handler: handler.getData
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false
  
  postData:
      handler: handler.postData
      events:
        - http:
            path: /
            method: post
            cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
                - X-Amzn-Trace-Id
              allowCredentials: false



